apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "pytorch-s3"
spec:
  default:
    predictor:
      serviceAccountName: serving
      pytorch:
        storageUri: "s3://nakfour/fddmodel/"
        modelClassName: "Net"
