apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "pytorchfraud"
spec:
  predictor:
    serviceAccountName: serving
    pytorch:
      storageUri: "s3://nakfour/fddmodel/"
      modelClassName: "Net"
