apiVersion: v1
kind: Secret
metadata:
  name: miniosecret
  annotations:
     serving.kubeflow.org/s3-endpoint: minio-service.kubeflow:9000 
     serving.kubeflow.org/s3-usehttps: "0" # by default 1, for testing with minio you need to set to 0
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serving
secrets:
  - name: miniosecret
