apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "pytorchfraud"
spec:
  predictor:
    serviceAccountName: serving
    minReplicas: 1
    timeout: 60
    batcher:
      maxBatchSize: 32
      maxLatency: 5000
    pytorch:
      storageUri: "s3://nakfour/fddmodel/"
      modelClassName: "Net"
