apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: nakfour
  name: pytorchjob-example
spec:
  parallelTrialCount: 2
  maxTrialCount: 5
  maxFailedTrialCount: 2
  objective:
    type: maximize
    goal: 0.80
    objectiveMetricName: avg_precision
  algorithm:
    algorithmName: grid
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
        step: "0.01"
    - name: n-hidden
      parameterType: int
      feasibleSpace:
        min: "12"
        max: "16"
        step: "2"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - "adam"
          - "sgd"
  trialTemplate:
    primaryContainerName: pytorch
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: numberHiddenNodes
        description: Number of nodes in each hidden layer
        reference: n-hidden
      - name: optimizer
        description: Type of optimizer to use
        reference: optimizer
    trialSpec:
      apiVersion: "kubeflow.org/v1"
      kind: PyTorchJob
      spec:
        pytorchReplicaSpecs:
          Master:
            replicas: 1
            restartPolicy: OnFailure
            template:
              spec:
                containers:
                  - name: pytorch
                    image: docker.io/nakfour/pytorch-fdd:1.3
                    imagePullPolicy: Always
                    command:
                      - "python"
                      - "/var/ccfraud.py"
                      - "--lr=${trialParameters.learningRate}"
                      - "--n-hidden=${trialParameters.numHiddenNodes}"
                      - "--optimizer=${trialParameters.optimizer}"

          Worker:
            replicas: 2
            restartPolicy: OnFailure
            template:
              spec:
                containers:
                  - name: pytorch
                    image: docker.io/nakfour/pytorch-fdd:1.3
                    imagePullPolicy: Always
                    command:
                      - "python"
                      - "/var/ccfraud.py"
                      - "--lr=${trialParameters.learningRate}"
                      - "--n-hidden=${trialParameters.numHiddenNodes}"
                      - "--optimizer=${trialParameters.optimizer}"
